#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Wrapper script to train a champollion_V1 self-supervised encoder for a sulcal region.
Invokes champollion/train.py via subprocess with Hydra overrides built from
pipeline-style paths. Requires dataset configs generated by generate_champollion_config.py.
"""

import os
from os.path import abspath, dirname, exists, join

from champollion_utils.script_builder import ScriptBuilder

from champollion_pipeline.derivatives_layout import compute_champollion_configs_root

_SCRIPT_DIR = dirname(abspath(__file__))
_CONTRASTIVE_DIR = abspath(join(_SCRIPT_DIR, "..", "..", "external", "champollion_V1", "champollion"))
_PIPELINE_DATA_DIR = abspath(join(_SCRIPT_DIR, "..", "..", "data"))
_SWF_UNSUPPORTED_MESSAGE = (
    "--swf is not supported yet by train_champollion: soma-workflow submission "
    "for training is not implemented. Re-run without --swf to train locally, "
    "or submit the command through a cluster scheduler script."
)


class TrainChampollion(ScriptBuilder):
    """Script for training a champollion_V1 encoder for a sulcal region."""

    def __init__(self):
        super().__init__(
            script_name="train_champollion",
            description=(
                "Train a champollion_V1 self-supervised encoder for a sulcal region. "
                "Dataset configs must have been generated first by "
                "generate_champollion_config.py."
            ),
        )
        (
            self.add_required_argument(
                "--dataset",
                "Dataset name — must match a directory in the dataset configs search path "
                "(built-in champollion_V1 configs, or a custom directory supplied with --config-dir).",
            )
            .add_required_argument(
                "--region",
                "Region config name, e.g. 'cingulate_left'. "
                "Must correspond to a YAML file under configs/dataset/{dataset}/.",
            )
            .add_optional_argument(
                "--config-dir",
                "Root of a Hydra configs directory searched for dataset configs in addition to "
                "the built-in champollion_V1 configs. Must contain dataset/{dataset}/{region}.yaml. "
                "Default: data/{dataset}/derivatives/champollion_V1/configs (where "
                "generate_champollion_config.py writes for crops under data/).",
                default=None,
            )
            .add_optional_argument(
                "--mode", "Training mode: 'encoder', 'classifier', or 'regresser'.", default="encoder"
            )
            .add_optional_argument(
                "--output_dir",
                "Directory for Hydra logs and model checkpoints. "
                "Defaults to data/{dataset}/derivatives/champollion_V1/models/{region}/.",
                default=None,
            )
            .add_optional_argument(
                "--njobs",
                "Number of CPU workers for the DataLoader (num_cpu_workers override).",
                default=None,
                type_=int,
            )
            .add_flag("--cpu", "Force CPU usage (sets CUDA_VISIBLE_DEVICES='').")
            .add_flag("--overwrite", "Re-train even if output directory already exists.")
            .add_flag(
                "--load-sparse",
                "Use sparse per-subject loading (requires coords_all in dataset config). "
                "Default: False — classic single .npy format as generated by generate_champollion_config.py.",
            )
            .add_optional_argument(
                "--localization",
                "Dataset localization preset to use (e.g. 'local', 'jean-zay'). "
                "Must match the value used in generate_champollion_config.py.",
                default="local",
            )
            .add_flag(
                "--swf",
                "Not supported yet: soma-workflow submission for training is not implemented; "
                "passing this flag makes the run fail immediately.",
            )
        )

    def _resolve_config_dir(self) -> str:
        """Return abspath(--config-dir) if given, else
        compute_champollion_configs_root(_PIPELINE_DATA_DIR, dataset). O(1)."""
        if self.args.config_dir:
            return abspath(self.args.config_dir)
        return compute_champollion_configs_root(_PIPELINE_DATA_DIR, self.args.dataset)

    def _resolve_output_dir(self):
        """Return absolute output path, defaulting to the pipeline derivatives tree."""
        if self.args.output_dir:
            return abspath(self.args.output_dir)
        return abspath(
            join(
                _SCRIPT_DIR,
                "..",
                "..",
                "data",
                self.args.dataset,
                "derivatives",
                "champollion_V1",
                "models",
                self.args.region,
            )
        )

    def _validate_inputs(self):
        """Check that the Hydra dataset config for this region exists."""
        builtin_path = join(_CONTRASTIVE_DIR, "configs", "dataset", self.args.dataset, f"{self.args.region}.yaml")
        local_path = join(self._resolve_config_dir(), "dataset", self.args.dataset, f"{self.args.region}.yaml")
        if not exists(local_path) and not exists(builtin_path):
            raise FileNotFoundError(
                f"Dataset config not found in either location:\n"
                f"  local   : {local_path}\n"
                f"  built-in: {builtin_path}\n"
                f"Run generate_champollion_config.py --dataset {self.args.dataset} first.\n"
                f"pass --config-dir for configs elsewhere"
            )

        valid_modes = ("encoder", "classifier", "regresser")
        if self.args.mode not in valid_modes:
            raise ValueError(f"Invalid --mode '{self.args.mode}'. Choose from: {', '.join(valid_modes)}.")

    def run(self):
        """Execute the training pipeline."""
        if self.args.swf:
            raise NotImplementedError(_SWF_UNSUPPORTED_MESSAGE)
        self._validate_inputs()

        local_dir = os.getcwd()
        original_cuda = os.environ.get("CUDA_VISIBLE_DEVICES")

        if self.args.cpu:
            os.environ["CUDA_VISIBLE_DEVICES"] = ""
            print("CPU mode enabled: CUDA_VISIBLE_DEVICES set to empty string")

        try:
            return self._run_training(local_dir)
        finally:
            if original_cuda is None:
                os.environ.pop("CUDA_VISIBLE_DEVICES", None)
            else:
                os.environ["CUDA_VISIBLE_DEVICES"] = original_cuda

    def _run_training(self, local_dir):
        """Run train.py from the champollion_V1 champollion package directory."""
        output_dir = self._resolve_output_dir()

        if exists(output_dir) and not self.args.overwrite:
            print(f"Output directory already exists: {output_dir}\nUse --overwrite to force retraining.")
            return 0

        os.makedirs(output_dir, exist_ok=True)
        os.chdir(_CONTRASTIVE_DIR)
        try:
            platform = "cpu" if self.args.cpu else "cuda"

            # Hydra command-line overrides
            # +dataset/{dataset}/{region}=null appends the generated region config
            overrides = [
                f"+dataset/{self.args.dataset}={self.args.region}",
                f"+dataset_localization={self.args.localization}",
                f"platform={platform}",
                f"mode={self.args.mode}",
                f"hydra.run.dir={output_dir}",
            ]

            config_dir = self._resolve_config_dir()
            overrides.append(f"hydra.searchpath=[file://{config_dir}]")
            # hydra.searchpath is appended after the primary config dir, so the built-in
            # local.yaml would take precedence over the one in config-dir. Override
            # dataset_folder directly to ensure the config-dir's value is used.
            local_yaml_path = join(config_dir, "dataset_localization", f"{self.args.localization}.yaml")
            if exists(local_yaml_path):
                with open(local_yaml_path) as _f:
                    for _line in _f:
                        if _line.strip().startswith("dataset_folder:"):
                            _dataset_folder = _line.split(":", 1)[1].strip()
                            # local.yaml uses @package _global_, so dataset_folder
                            # is at the config root, not nested under dataset_localization.
                            overrides.append(f"++dataset_folder={_dataset_folder}")
                            break

            overrides.append(f"load_sparse={'true' if self.args.load_sparse else 'false'}")

            if self.args.njobs is not None:
                overrides.append(f"num_cpu_workers={self.args.njobs}")

            cmd = ["python3", "train.py"] + overrides
            return self.execute_command(cmd, shell=False)
        finally:
            os.chdir(local_dir)


def main():
    """Main entry point."""
    script = TrainChampollion()
    return script.build().print_args().run()


if __name__ == "__main__":
    exit(main())
