#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Wrapper script to train a champollion_V1 self-supervised encoder for a sulcal region.
Invokes contrastive/train.py via subprocess with Hydra overrides built from
pipeline-style paths. Requires dataset configs generated by generate_champollion_config.py.
"""

import os
from os.path import abspath, dirname, exists, join

from champollion_utils.script_builder import ScriptBuilder

_SCRIPT_DIR = dirname(abspath(__file__))
_CONTRASTIVE_DIR = abspath(join(_SCRIPT_DIR, '..', 'external', 'champollion_V1', 'contrastive'))


class TrainChampollion(ScriptBuilder):
    """Script for training a champollion_V1 encoder for a sulcal region."""

    def __init__(self):
        super().__init__(
            script_name="train_champollion",
            description=(
                "Train a champollion_V1 self-supervised encoder for a sulcal region. "
                "Dataset configs must have been generated first by "
                "generate_champollion_config.py."
            )
        )
        (self.add_required_argument(
            "--dataset",
            "Dataset name — must match a directory in the dataset configs search path "
            "(built-in champollion_V1 configs, or a custom directory supplied with --config-dir).")
         .add_required_argument(
            "--region",
            "Region config name, e.g. 'cingulate_left'. "
            "Must correspond to a YAML file under configs/dataset/{dataset}/.")
         .add_optional_argument(
            "--config-dir",
            "Root of a local Hydra configs directory to search for dataset configs, "
            "in addition to the built-in champollion_V1 configs. "
            "Must contain a dataset/{dataset}/{region}.yaml layout.",
            default=None)
         .add_optional_argument(
            "--mode",
            "Training mode: 'encoder', 'classifier', or 'regresser'.",
            default="encoder")
         .add_optional_argument(
            "--output_dir",
            "Directory for Hydra logs and model checkpoints. "
            "Defaults to data/{dataset}/derivatives/champollion_V1/models/{region}/.",
            default=None)
         .add_optional_argument(
            "--njobs",
            "Number of CPU workers for the DataLoader (num_cpu_workers override).",
            default=None, type_=int)
         .add_flag("--cpu", "Force CPU usage (sets CUDA_VISIBLE_DEVICES='').")
         .add_flag("--overwrite", "Re-train even if output directory already exists.")
         .add_flag(
            "--load-sparse",
            "Use sparse per-subject loading (requires coords_all in dataset config). "
            "Default: False — classic single .npy format as generated by generate_champollion_config.py.")
         .add_flag(
            "--swf",
            "Submit via soma-workflow for scheduling on Neurospin HPC clusters."))

    def _resolve_output_dir(self):
        """Return absolute output path, defaulting to the pipeline derivatives tree."""
        if self.args.output_dir:
            return abspath(self.args.output_dir)
        return abspath(join(
            _SCRIPT_DIR, '..', '..', 'data',
            self.args.dataset, 'derivatives', 'champollion_V1',
            'models', self.args.region
        ))

    def _validate_inputs(self):
        """Check that the Hydra dataset config for this region exists."""
        builtin_path = join(
            _CONTRASTIVE_DIR, 'configs', 'dataset',
            self.args.dataset, f"{self.args.region}.yaml"
        )
        config_dir = self.args.config_dir
        if config_dir:
            local_path = join(
                abspath(config_dir), 'dataset',
                self.args.dataset, f"{self.args.region}.yaml"
            )
            if not exists(local_path) and not exists(builtin_path):
                raise FileNotFoundError(
                    f"Dataset config not found in either location:\n"
                    f"  local   : {local_path}\n"
                    f"  built-in: {builtin_path}\n"
                    f"Run generate_champollion_config.py --dataset {self.args.dataset} first."
                )
        else:
            if not exists(builtin_path):
                raise FileNotFoundError(
                    f"Dataset config not found: {builtin_path}\n"
                    f"Run generate_champollion_config.py --dataset {self.args.dataset} first.\n"
                    f"For configs stored outside champollion_V1, supply --config-dir."
                )

        valid_modes = ('encoder', 'classifier', 'regresser')
        if self.args.mode not in valid_modes:
            raise ValueError(
                f"Invalid --mode '{self.args.mode}'. "
                f"Choose from: {', '.join(valid_modes)}."
            )

    def run(self):
        """Execute the training pipeline."""
        self._validate_inputs()

        local_dir = os.getcwd()
        original_cuda = os.environ.get("CUDA_VISIBLE_DEVICES")

        if self.args.cpu:
            os.environ["CUDA_VISIBLE_DEVICES"] = ""
            print("CPU mode enabled: CUDA_VISIBLE_DEVICES set to empty string")

        try:
            return self._run_training(local_dir)
        finally:
            if original_cuda is None:
                os.environ.pop("CUDA_VISIBLE_DEVICES", None)
            else:
                os.environ["CUDA_VISIBLE_DEVICES"] = original_cuda

    def _run_training(self, local_dir):
        """Run train.py from the champollion contrastive directory."""
        output_dir = self._resolve_output_dir()

        if exists(output_dir) and not self.args.overwrite:
            print(
                f"Output directory already exists: {output_dir}\n"
                "Use --overwrite to force retraining."
            )
            return 0

        os.makedirs(output_dir, exist_ok=True)
        os.chdir(_CONTRASTIVE_DIR)

        platform = "cpu" if self.args.cpu else "cuda_not_brainvisa"

        # Hydra command-line overrides
        # +dataset/{dataset}/{region}=null appends the generated region config
        overrides = [
            f"+dataset/{self.args.dataset}={self.args.region}",
            "+dataset_localization=local",
            f"platform={platform}",
            f"mode={self.args.mode}",
            f"hydra.run.dir={output_dir}",
        ]

        if self.args.config_dir:
            overrides.append(
                f"hydra.searchpath=[file://{abspath(self.args.config_dir)}]"
            )

        overrides.append(f"load_sparse={'true' if self.args.load_sparse else 'false'}")

        if self.args.njobs is not None:
            overrides.append(f"num_cpu_workers={self.args.njobs}")

        cmd = ["python3", "train.py"] + overrides
        result = self.execute_command(cmd, shell=False)

        os.chdir(local_dir)
        return result


def main():
    """Main entry point."""
    script = TrainChampollion()
    return script.build().print_args().run()


if __name__ == "__main__":
    exit(main())
